//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.10 at 05:24:27 PM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import org.multigraph.AxisOrientation;

public class Adapter1
    extends XmlAdapter<String, AxisOrientation>
{


    public AxisOrientation unmarshal(String value) {
        return (org.multigraph.AxisOrientation.parse(value));
    }

    public String marshal(AxisOrientation value) {
        return (org.multigraph.AxisOrientation.toString(value));
    }

}
