//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 12:44:02 PM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter5
    extends XmlAdapter<java.lang.String, org.multigraph.DataValue.String>
{


    public org.multigraph.DataValue.String unmarshal(java.lang.String value) {
        return (org.multigraph.DataValue.String.parse(value));
    }

    public java.lang.String marshal(org.multigraph.DataValue.String value) {
        return (org.multigraph.DataValue.String.toString(value));
    }

}
