//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.24 at 11:56:19 PM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import org.multigraph.DPoint;

public class Adapter3
    extends XmlAdapter<String, DPoint>
{


    public DPoint unmarshal(String value) {
        return (org.multigraph.DPoint.parse(value));
    }

    public String marshal(DPoint value) {
        return (org.multigraph.DPoint.toString(value));
    }

}
