//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.03 at 09:48:11 AM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.adapters.XmlAdapter;

import org.multigraph.datatypes.string.StringValue;

public class Adapter4
    extends XmlAdapter<java.lang.String, org.multigraph.datatypes.string.StringValue>
{


    public org.multigraph.datatypes.string.StringValue unmarshal(java.lang.String value) {
        return (org.multigraph.datatypes.string.StringValue.parse(value));
    }

    public java.lang.String marshal(org.multigraph.datatypes.string.StringValue value) {
        return (org.multigraph.datatypes.string.StringValue.toString(value));
    }

}
