//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.25 at 09:07:43 AM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Muglatrix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Muglatrix">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="foo" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="bar" type="{http://www.w3.org/2001/XMLSchema}int" default="9" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Muglatrix")
public class Muglatrix {

    @XmlAttribute(name = "foo")
    protected Integer foo;
    @XmlAttribute(name = "bar")
    protected Integer bar;

    /**
     * Gets the value of the foo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFoo() {
        if (foo == null) {
            return  2;
        } else {
            return foo;
        }
    }

    /**
     * Sets the value of the foo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFoo(int value) {
        this.foo = value;
    }

    public boolean isSetFoo() {
        return (this.foo!= null);
    }

    public void unsetFoo() {
        this.foo = null;
    }

    /**
     * Gets the value of the bar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBar() {
        if (bar == null) {
            return  9;
        } else {
            return bar;
        }
    }

    /**
     * Sets the value of the bar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBar(int value) {
        this.bar = value;
    }

    public boolean isSetBar() {
        return (this.bar!= null);
    }

    public void unsetBar() {
        this.bar = null;
    }

}
