//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.01 at 03:16:16 PM EST 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.multigraph.RGBColor;


/**
 * <p>Java class for Plotarea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plotarea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="border" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="bordercolor" type="{}RGBColor" default="0xeeeeee" />
 *       &lt;attribute name="marginbottom" type="{http://www.w3.org/2001/XMLSchema}int" default="35" />
 *       &lt;attribute name="marginleft" type="{http://www.w3.org/2001/XMLSchema}int" default="38" />
 *       &lt;attribute name="margintop" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
 *       &lt;attribute name="marginright" type="{http://www.w3.org/2001/XMLSchema}int" default="35" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plotarea")
public class Plotarea {

    @XmlAttribute(name = "border")
    protected Integer border;
    @XmlAttribute(name = "bordercolor")
    @XmlJavaTypeAdapter(Adapter2 .class)
    protected RGBColor bordercolor;
    @XmlAttribute(name = "marginbottom")
    protected Integer marginbottom;
    @XmlAttribute(name = "marginleft")
    protected Integer marginleft;
    @XmlAttribute(name = "margintop")
    protected Integer margintop;
    @XmlAttribute(name = "marginright")
    protected Integer marginright;

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBorder() {
        if (border == null) {
            return  0;
        } else {
            return border;
        }
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBorder(int value) {
        this.border = value;
    }

    public boolean isSetBorder() {
        return (this.border!= null);
    }

    public void unsetBorder() {
        this.border = null;
    }

    /**
     * Gets the value of the bordercolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public RGBColor getBordercolor() {
        if (bordercolor == null) {
            return new Adapter2().unmarshal("0xeeeeee");
        } else {
            return bordercolor;
        }
    }

    /**
     * Sets the value of the bordercolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBordercolor(RGBColor value) {
        this.bordercolor = value;
    }

    public boolean isSetBordercolor() {
        return (this.bordercolor!= null);
    }

    /**
     * Gets the value of the marginbottom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMarginbottom() {
        if (marginbottom == null) {
            return  35;
        } else {
            return marginbottom;
        }
    }

    /**
     * Sets the value of the marginbottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarginbottom(int value) {
        this.marginbottom = value;
    }

    public boolean isSetMarginbottom() {
        return (this.marginbottom!= null);
    }

    public void unsetMarginbottom() {
        this.marginbottom = null;
    }

    /**
     * Gets the value of the marginleft property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMarginleft() {
        if (marginleft == null) {
            return  38;
        } else {
            return marginleft;
        }
    }

    /**
     * Sets the value of the marginleft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarginleft(int value) {
        this.marginleft = value;
    }

    public boolean isSetMarginleft() {
        return (this.marginleft!= null);
    }

    public void unsetMarginleft() {
        this.marginleft = null;
    }

    /**
     * Gets the value of the margintop property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMargintop() {
        if (margintop == null) {
            return  10;
        } else {
            return margintop;
        }
    }

    /**
     * Sets the value of the margintop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMargintop(int value) {
        this.margintop = value;
    }

    public boolean isSetMargintop() {
        return (this.margintop!= null);
    }

    public void unsetMargintop() {
        this.margintop = null;
    }

    /**
     * Gets the value of the marginright property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMarginright() {
        if (marginright == null) {
            return  35;
        } else {
            return marginright;
        }
    }

    /**
     * Sets the value of the marginright property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarginright(int value) {
        this.marginright = value;
    }

    public boolean isSetMarginright() {
        return (this.marginright!= null);
    }

    public void unsetMarginright() {
        this.marginright = null;
    }

}
