//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 01:07:57 PM EDT 
//


package org.multigraph.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Plot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="horizontalaxis" type="{}PlotAxis" minOccurs="0"/>
 *         &lt;element name="verticalaxis" type="{}PlotAxis" minOccurs="0"/>
 *         &lt;element name="renderer" type="{}Renderer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plot", propOrder = {
    "horizontalaxis",
    "verticalaxis",
    "renderer"
})
public class Plot {

    protected PlotAxis horizontalaxis;
    protected PlotAxis verticalaxis;
    protected Renderer renderer;

    /**
     * Gets the value of the horizontalaxis property.
     * 
     * @return
     *     possible object is
     *     {@link PlotAxis }
     *     
     */
    public PlotAxis getHorizontalaxis() {
        return horizontalaxis;
    }

    /**
     * Sets the value of the horizontalaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlotAxis }
     *     
     */
    public void setHorizontalaxis(PlotAxis value) {
        this.horizontalaxis = value;
    }

    public boolean isSetHorizontalaxis() {
        return (this.horizontalaxis!= null);
    }

    /**
     * Gets the value of the verticalaxis property.
     * 
     * @return
     *     possible object is
     *     {@link PlotAxis }
     *     
     */
    public PlotAxis getVerticalaxis() {
        return verticalaxis;
    }

    /**
     * Sets the value of the verticalaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlotAxis }
     *     
     */
    public void setVerticalaxis(PlotAxis value) {
        this.verticalaxis = value;
    }

    public boolean isSetVerticalaxis() {
        return (this.verticalaxis!= null);
    }

    /**
     * Gets the value of the renderer property.
     * 
     * @return
     *     possible object is
     *     {@link Renderer }
     *     
     */
    public Renderer getRenderer() {
        return renderer;
    }

    /**
     * Sets the value of the renderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Renderer }
     *     
     */
    public void setRenderer(Renderer value) {
        this.renderer = value;
    }

    public boolean isSetRenderer() {
        return (this.renderer!= null);
    }

}
